baseurl = "http://thomasbabuj.me"
languageCode = "en-us"
title = "Joseph Thomas Babu"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
	description = "This is my personal blog, updated infrequently with stuff I've been doing or thinking about."
	cover = "images/cover.jpg"
	githubName = "thomasbabuj"
    twitterName = "thomasbabuj"
  	author = "Joseph Thomas Babu"
  	authorlocation = "Singapore"
  	authorwebsite = "http://thomasbabuj.me"
  	hideHUGOSupport = false
  	[[menu.main]]
	  name = "My Blog"
	  weight = -120
	  identifier = "blog"
	  url = "/"
	[[menu.main]]
	  name = "About me"
	  weight = -110
	  identifier = "about"
	  url = "/about"
  

